openapi: 3.1.0
info:
  title: recipe sample data
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000'
paths:
  /recipe/list:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Recipe'
              examples:
                sample1:
                  $ref: '#/components/examples/GetRecipeList'
          headers:
            Access-Control-Allow-Origin: "http://localhost:3000/"
      operationId: get-recipe-list
components:
  schemas:
    Recipe:
      title: Recipe
      description: ''
      examples: []
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        rate:
          type: number
        deleted:
          type: boolean
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/Ingredient'
        steps:
          type: array
          items:
            type: string
    Ingredient:
      title: Ingredient
      type: object
      properties:
        name:
          type: string
        amount:
          type: number
        measurement:
          type: string
  securitySchemes: {}
  requestBodies: {}
  responses: {}
  examples:
    GetRecipeList:
      $ref: ./data/recipe-list.json
